/**
 * Englische Fassung aller Texte, die aus der Sammlung und aus dem
 * Regelwerk in die Oberfläche kommen.
 *
 * Der Schlüssel ist der deutsche Originaltext, Zeile für Zeile. Das hat
 * zwei Vorteile: gleiche Zeilen — „Ist jemand nicht fertig? - ACHTUNG!“
 * steht in fast jeder Disziplin — werden nur einmal übersetzt, und eine
 * neue Zeile im Datensatz fällt sofort auf, weil der Test in
 * test/uebersetzung.test.js jeden Text ohne Eintrag meldet.
 *
 * Die Übersetzung bleibt so nah am Original wie möglich. Fachbegriffe
 * folgen dem englischen Sprachgebrauch auf dem Stand: Pfosten = barricade,
 * Scheibe = target, Schuss = round, stehend frei = standing unsupported,
 * Durchgang = run, Trefferaufnahme = scoring.
 *
 * Eine weitere Sprache braucht nur eine weitere Datei dieser Bauart.
 */

export const TEXTE_EN = {
  // ── Schusszahlen, Anschläge, Stationszeilen aus der Sammlung ────────────
  "- 6 Schuss kniend": "- 6 rounds kneeling",
  "- 6 Schuss sitzend": "- 6 rounds seated",
  "- 6 Schuss stehend, linke Hand, Pfosten links": "- 6 rounds standing, left hand, left barricade",
  "- 6 Schuss stehend, rechte Hand, Pfosten rechts": "- 6 rounds standing, right hand, right barricade",
  "„Double action“ gilt nicht beim Gebrauch halbautomatischer Pistolen.": "“Double action” does not apply when semi-automatic pistols are used.",
  "(Match-Ende - Trefferaufnahme)": "(end of match - scoring)",
  "1 x 6 Schuss - stehend frei - in 12 Sekunden": "1 × 6 rounds - standing unsupported - in 12 seconds",
  "1. Durchgang - Wiederholung wird angesagt": "1st run - the repeat will be announced",
  "10 m: 2 × 5 Schüsse in Intervallen. Die Scheibe zeigt sich dreimal für je 2 Sekunden, dabei höchstens 2 Schüsse je Intervall (2-2-1, 2-1-2 oder 1-2-2).": "10 m: 2 × 5 rounds in intervals. The target faces three times for 2 seconds each, with at most 2 rounds per interval (2-2-1, 2-1-2 or 1-2-2).",
  "10 m: 2 × 5 Schüsse in Intervallen. Die Scheibe zeigt sich fünfmal für je 2 Sekunden, dabei jeweils 1 Schuss.": "10 m: 2 × 5 rounds in intervals. The target faces five times for 2 seconds each, with 1 round each time.",
  "10 m: 3 × 2 Schüsse in Intervallen. Die Scheibe zeigt sich dreimal für je 3 Sekunden, dabei jeweils 2 Schüsse.": "10 m: 3 × 2 rounds in intervals. The target faces three times for 3 seconds each, with 2 rounds each time.",
  "10 m: 6 Schüsse in 6 Sekunden, davon 3 auf jede Scheibe.": "10 m: 6 rounds in 6 seconds, 3 of them on each target.",
  "10 m: 6 Schüsse in 8 Sekunden.": "10 m: 6 rounds in 8 seconds.",
  "10 m: 6 Schüsse in Intervallen. Die Scheibe zeigt sich dreimal für je 2 Sekunden, dabei jeweils 2 Schüsse.": "10 m: 6 rounds in intervals. The target faces three times for 2 seconds each, with 2 rounds each time.",
  "12 Schuss in 2 Minuten": "12 rounds in 2 minutes",
  "12 Schuss, bzw. 2x6 Schuss in 120 Sekunden.": "12 rounds, or 2×6 rounds, in 120 seconds.",
  "12 Schüsse stehend frei": "12 rounds standing unsupported",
  "15 m: 2 × 5 Schüsse in 100 Sekunden einschließlich eigenständigem Nachladen.": "15 m: 2 × 5 rounds in 100 seconds including an unprompted reload.",
  "15 m: 2 × 5 Schüsse in Intervallen. Die Scheibe zeigt sich fünfmal für je 2 Sekunden, dabei jeweils 1 Schuss.": "15 m: 2 × 5 rounds in intervals. The target faces five times for 2 seconds each, with 1 round each time.",
  "15 m: 2 × 5 Schüsse in Intervallen. Die Scheibe zeigt sich fünfmal für je 3 Sekunden, dabei jeweils 1 Schuss.": "15 m: 2 × 5 rounds in intervals. The target faces five times for 3 seconds each, with 1 round each time.",
  "15 m: 2 × 6 Schüsse in Intervallen. Die Scheibe zeigt sich sechsmal für je 2 Sekunden, dabei jeweils 1 Schuss. Danach Nachladen und erneuter Durchgang.": "15 m: 2 × 6 rounds in intervals. The target faces six times for 2 seconds each, with 1 round each time. Then reload and a second run.",
  "15 m: 2 × 6 Schüsse in Intervallen. Die Scheibe zeigt sich sechsmal für je 3 Sekunden, dabei jeweils 1 Schuss. Danach Nachladen und erneuter Durchgang.": "15 m: 2 × 6 rounds in intervals. The target faces six times for 3 seconds each, with 1 round each time. Then reload and a second run.",
  "15 m: 3 × 2 Schüsse in Intervallen. Die Scheibe zeigt sich dreimal für je 3 Sekunden, dabei jeweils 2 Schüsse.": "15 m: 3 × 2 rounds in intervals. The target faces three times for 3 seconds each, with 2 rounds each time.",
  "15 m: 6 Schüsse in Intervallen auf die rechte Scheibe. Die Scheibe zeigt sich dreimal für je 3 Sekunden, dabei jeweils 2 Schüsse.": "15 m: 6 rounds in intervals on the right-hand target. The target faces three times for 3 seconds each, with 2 rounds each time.",
  "150 Schuss auf fünf Matches verteilt": "150 rounds spread over five matches",
  "165 Sekunden": "165 seconds",
  "2 × 5, mit Magazinwechsel": "2 × 5, with a magazine change",
  "2 × 6 Schüsse stehend frei, nur double action.": "2 × 6 rounds standing unsupported, double action only.",
  "2 × 6 Schüsse stehend frei.": "2 × 6 rounds standing unsupported.",
  "2 Schuss in 3 Sekunden mit 3 Wiederholungen auf die rechte Scheibe.": "2 rounds in 3 seconds with 3 repeats on the right-hand target.",
  "2 x 6 Schuss  - stehend frei - in 20 Sek. inkl. Nachladen": "2 × 6 rounds - standing unsupported - in 20 sec. including the reload",
  "2 x 6 Schuss - stehend frei - in 35 Sek. inkl. Nachladen": "2 × 6 rounds - standing unsupported - in 35 sec. including the reload",
  "2. Durchgang": "2nd run",
  "20 m: 2 × 5 Schüsse in 100 Sekunden einschließlich eigenständigem Nachladen.": "20 m: 2 × 5 rounds in 100 seconds including an unprompted reload.",
  "20 m: 6 Schüsse in 10 Sekunden, davon 3 auf jede Scheibe.": "20 m: 6 rounds in 10 seconds, 3 of them on each target.",
  "20 m: 6 Schüsse in 10 Sekunden.": "20 m: 6 rounds in 10 seconds.",
  "24 Patronen Großkaliber": "24 centrefire cartridges",
  "24 Schuss in 2 Minuten": "24 rounds in 2 minutes",
  "24 Schuss in 3 Minuten": "24 rounds in 3 minutes",
  "25 m: 12 Schüsse in 2 Minuten einschließlich eines eventuellen Nachladens.": "25 m: 12 rounds in 2 minutes including any reload.",
  "25 m: 12 Schüsse in 2 Minuten einschließlich eines eventuellen Nachladens. Jetloader und Speedloader sind erlaubt.": "25 m: 12 rounds in 2 minutes including any reload. Jetloaders and speedloaders are permitted.",
  "25 m: 2 × 5 Schüsse in 2 Minuten einschließlich eines eventuellen Nachladens.": "25 m: 2 × 5 rounds in 2 minutes including any reload.",
  "25 m: 6 Schüsse in 15 Sekunden auf die linke Scheibe.": "25 m: 6 rounds in 15 seconds on the left-hand target.",
  "25 m: 6 Schüsse in 15 Sekunden.": "25 m: 6 rounds in 15 seconds.",
  "25 Meter/Yards - 12 Sekunden - nur double action": "25 metres/yards - 12 seconds - double action only",
  "25 Meter/Yards - 90 Sekunden - nur double action": "25 metres/yards - 90 seconds - double action only",
  "2x (5x 1 Schuss in 2s)": "2× (5× 1 round in 2s)",
  "2x (5x 1 Schuss in 3s)": "2× (5× 1 round in 3s)",
  "2x (max. 2-2-1 Schuss in 3x 2s)": "2× (max. 2-2-1 rounds in 3× 2s)",
  "2x 5 Schuss in 100 Sekunden": "2× 5 rounds in 100 seconds",
  "2x 5 Schuss in 120 Sekunden": "2× 5 rounds in 120 seconds",
  "2x 6 Schuss in 5 Sekunden": "2× 6 rounds in 5 seconds",
  "3 x 6 Schuss in 90 Sek. inkl. Nachladen": "3 × 6 rounds in 90 sec. including the reload",
  "30 Patronen": "30 cartridges",
  "30 Patronen, keine Wadcutter": "30 cartridges, no wadcutters",
  "30 Patronen, mindestens 1200 Joule": "30 cartridges, at least 1200 joules",
  "3x 2 Schuss in 2 Sekunden.": "3× 2 rounds in 2 seconds.",
  "3x 2 Schuss in 3 Sekunden": "3× 2 rounds in 3 seconds",
  "4 x 6 Schuss in 165 Sek. inkl. Nachladen": "4 × 6 rounds in 165 sec. including the reload",
  "5 einhändig rechte Scheibe, 5 beidhändig linke Scheibe": "5 one-handed on the right-hand target, 5 two-handed on the left-hand target",
  "5 rechts, 5 links am Pfosten vorbei": "5 to the right, 5 to the left past the barricade",
  "50 Meter/Yards - 165 Sekunden - auch single action erlaubt": "50 metres/yards - 165 seconds - single action also permitted",
  "6 Schuss in 10 Sekunden": "6 rounds in 10 seconds",
  "6 Schuss in 10 Sekunden davon 3 auf jede Scheibe.": "6 rounds in 10 seconds, 3 of them on each target.",
  "6 Schuss in 15 Sekunden": "6 rounds in 15 seconds",
  "6 Schuss in 15 Sekunden auf die linke Scheibe.": "6 rounds in 15 seconds on the left-hand target.",
  "6 Schuss in 6 Sekunden": "6 rounds in 6 seconds",
  "6 Schuss in 6 Sekunden davon 3 auf jede Scheibe.": "6 rounds in 6 seconds, 3 of them on each target.",
  "6 Schuss in 8 Sekunden": "6 rounds in 8 seconds",
  "6 Schuss kniend": "6 rounds kneeling",
  "6 Schuss liegend": "6 rounds prone",
  "6 Schuss stehend frei": "6 rounds standing unsupported",
  "6 Schuss stehend freihändig.": "6 rounds standing unsupported.",
  "6 Schuss stehend, linke Hand, Pfosten links": "6 rounds standing, left hand, left barricade",
  "6 Schuss stehend, rechte Hand, Pfosten rechts": "6 rounds standing, right hand, right barricade",
  "6 Schüsse kniend frei": "6 rounds kneeling unsupported",
  "6 Schüsse liegend": "6 rounds prone",
  "6 Schüsse sitzend": "6 rounds seated",
  "6 Schüsse stehend frei": "6 rounds standing unsupported",
  "6 Schüsse stehend frei, nur double action.": "6 rounds standing unsupported, double action only.",
  "6 Schüsse stehend, linke Hand, Pfosten links": "6 rounds standing, left hand, left barricade",
  "6 Schüsse stehend, rechte Hand, Pfosten rechts": "6 rounds standing, right hand, right barricade",
  "60 Patronen, dazu 6 Probeschüsse": "60 cartridges, plus 6 sighting shots",
  "6x 1 Schuss in 2 Sekunden": "6× 1 round in 2 seconds",
  "6x 1 Schuss in 2 Sekunden.": "6× 1 round in 2 seconds.",
  "6x 1 Schuss in 3 Sekunden": "6× 1 round in 3 seconds",
  "7 m: 2 × 5 Schüsse in Intervallen. Die Scheibe zeigt sich dreimal für je 2 Sekunden, dabei höchstens 2 Schüsse je Intervall (2-2-1, 2-1-2 oder 1-2-2).": "7 m: 2 × 5 rounds in intervals. The target faces three times for 2 seconds each, with at most 2 rounds per interval (2-2-1, 2-1-2 or 1-2-2).",
  "7 Meter/Yards - 20 Sekunden - nur double action": "7 metres/yards - 20 seconds - double action only",
  "90 Sekunden": "90 seconds",
  "Ab dieser Station darf nur noch ein Magazin benutzt werden, das wieder gefüllt werden muss; für den Revolver kein Schnelllader mehr (C.17.9).": "From this station on, only one magazine may be used and it has to be refilled; no speedloader for the revolver any more (C.17.9).",
  "Auch ein langanhaltender Pfiff. Das Schießen wird augenblicklich eingestellt.": "A long sustained whistle counts as well. Firing stops immediately.",
  "Auch single action erlaubt.": "Single action also permitted.",
  "Auf das Startsignal ziehen und stehend mit der rechten Hand rechts am Pfosten vorbei schießen.": "On the start signal, draw and fire standing with the right hand past the right-hand side of the barricade.",
  "Auf das Startsignal ziehen und stehend schießen, ohne zu spannen bzw. nach dem Durchladen.": "On the start signal, draw and fire standing, without cocking or after chambering.",
  "Auf das Startsignal ziehen, Anschlag kniend einnehmen und schießen.": "On the start signal, draw, take up the kneeling position and fire.",
  "Auf das Startsignal ziehen, Anschlag liegend einnehmen, erster Schuss ohne zu spannen bzw. nach dem Durchladen.": "On the start signal, draw, take up the prone position, first round without cocking or after chambering.",
  "Auf das Startsignal ziehen, Anschlag stehend einnehmen und alle fünf Schüsse in zehn Sekunden abgeben.": "On the start signal, draw, take up the standing position and fire all five rounds within ten seconds.",
  "Auf das Startsignal ziehen, auf den Boden setzen und schießen, ohne zu spannen bzw. nach dem Durchladen.": "On the start signal, draw, sit down on the ground and fire, without cocking or after chambering.",
  "Auf das Startsignal ziehen, das Schlagstück von Hand spannen und stehend einhändig auf die obere rechte Ringscheibe schießen.": "On the start signal, draw, cock the hammer by hand and fire standing one-handed at the upper right scoring target.",
  "Auf den Stationen B und C ist die gesamte Munition am Schützen mitzuführen. Geladen werden darf nur ein Reservemagazin bzw. ein Speedloader mit je 6 Patronen, die restlichen 12 Patronen lose in Tasche, Patronenhalter oder am Gürtel.": "On stations B and C the shooter carries all the ammunition. Only one spare magazine or speedloader may be loaded, with 6 cartridges each; the remaining 12 cartridges go loose in a pocket, a cartridge holder or on the belt.",
  "Auf Kommando auf die 1-m-Linie vorgehen.": "On command, move forward to the 1 m line.",
  "Ausnahme zu C.17.12: Hier darf die Waffe vor dem Startsignal am Griffstück erfasst werden.": "Exception to C.17.12: here the weapon may be gripped before the start signal.",
  "BDMP 1020": "BDMP 1020",
  "BDMP 1500 (PPC)": "BDMP 1500 (PPC)",
  "BDMP 1500 (PPC) und BDMP 1020": "BDMP 1500 (PPC) and BDMP 1020",
  "BDMP 1500 / 1020 (C.8.5)": "BDMP 1500 / 1020 (C.8.5)",
  "BDMP 1500 Carbine": "BDMP 1500 Carbine",
  "BDMP 1500 Matches 1-5 C.8.2": "BDMP 1500 Matches 1-5 C.8.2",
  "BDMP-1500-Scheibe je Schütze und Match": "one BDMP 1500 target per shooter and match",
  "Bei zwei Scheiben: Station 1 und 3 auf die linke, Station 2 und 4 auf die rechte Scheibe.": "With two targets: stations 1 and 3 on the left-hand target, stations 2 and 4 on the right-hand one.",

  // ── Stellungen, Sicherheit, Ablaufregeln ────────────────────────────────
  "Beide Gesäßbacken auf dem Boden, der Körper den Scheiben zugewandt. Eine Hand kann stützen, der Ellenbogen darf den Boden nicht berühren, der Rücken ebenfalls nicht. Ein oder beide Knie dürfen angewinkelt sein. Die Waffe darf nicht durch einen Fuß unterstützt werden. Der Pfosten darf nicht benutzt werden.": "Both buttocks on the ground, the body facing the targets. One hand may support, but the elbow must not touch the ground, nor may the back. One or both knees may be bent. The weapon must not be supported by a foot. The barricade must not be used.",
  "Beim Einnehmen aller Stellungen zeigt die Mündung immer in Richtung Geschossfang.": "While taking up any position the muzzle always points towards the backstop.",
  "Beim Nachladen muss die Pistole geholstert sein — Verschluss hinten oder geschlossen und abgeschlagen. Der Revolver wird direkt in die Trommel nachgeladen.": "For the reload the pistol has to be holstered — slide locked back, or closed with the hammer down. The revolver is reloaded directly into the cylinder.",
  "Beim Wechsel von kniend in stehend, sitzend in liegend und liegend in stehend muss die halbautomatische Pistole mit zurückgezogenem Schlitten und entferntem Magazin geführt werden, der Revolver mit geöffneter Trommel und entfernten Hülsen.": "When changing from kneeling to standing, from seated to prone and from prone to standing, the semi-automatic pistol is carried with the slide locked back and the magazine removed, the revolver with the cylinder open and the cases removed.",
  "Beim Wechsel von sitzend in liegend muss die Waffe nach vorn in Richtung Geschossfang zeigen.": "When changing from seated to prone the weapon must point forward towards the backstop.",
  "Dazu die Waffen laden und Holstern.": "Load and holster your weapons for this.",
  "Der Abzugsfinger befindet sich dabei deutlich erkennbar außerhalb des Abzugsbügels.": "The trigger finger stays visibly outside the trigger guard while doing so.",
  "Der Fuß muss Kontakt zur Verlängerung der seitlichen Begrenzung haben.": "The foot has to stay in contact with the extension of the lateral boundary.",
  "Der Körper liegt ausgestreckt in Sichtlinie, den Kopf zum Ziel; schräges Liegen ist zulässig, solange die Linie gewahrt bleibt und niemand gestört wird. Die Waffe darf durch eine oder beide am Boden aufliegende Hände unterstützt werden, darf aber selbst keinen Bodenkontakt haben. Der Pfosten darf nicht benutzt werden.": "The body lies stretched out along the line of sight, head towards the target; lying at an angle is permitted as long as the line is kept and nobody is disturbed. The weapon may be supported by one or both hands resting on the ground, but must not touch the ground itself. The barricade must not be used.",
  "Der Pfosten darf als Unterstützung dienen, die Waffe darf ihn jedoch nicht berühren.": "The barricade may be used as support, but the weapon must not touch it.",
  "Der Pfosten ist als Unterstützung zu benutzen, die Waffe selbst darf ihn nicht berühren. Der Schütze steht rechts hinter dem Pfosten, wenn er links schießt, und umgekehrt. Die gedachte oder markierte Linie an der Schussseite des Balkens darf nicht übertreten werden. Das Schießen am Pfosten beginnt mit der linken Hand; abgezogen wird mit einem Finger derselben Hand. Nur der Abzugsfinger befindet sich im Abzugsbügel, die schießende Hand darf durch die andere unterstützt werden.": "The barricade has to be used as support, but the weapon must not touch it. The shooter stands to the right behind the barricade when shooting on the left, and the other way round. The imaginary or marked line on the firing side of the post must not be crossed. Barricade shooting starts with the left hand; the trigger is pulled with a finger of that same hand. Only the trigger finger is inside the trigger guard, and the shooting hand may be supported by the other one.",
  "Der Schütze steht aufrecht, die geladene Waffe im Holster; halbautomatische Pistolen unterladen. Arme und Hände hängen zwanglos herab und berühren weder Waffe noch Holster, bis sich die Scheiben herdrehen oder ein anderes Startsignal gegeben wird. Eine abweichende Handposition zum Starten eines Timers am Arm oder Pfosten ist zulässig.": "The shooter stands upright with the loaded weapon in the holster; semi-automatic pistols holstered with an empty chamber. Arms and hands hang down loosely and touch neither weapon nor holster until the targets turn or another start signal is given. A different hand position for starting a timer on the arm or the barricade is permitted.",
  "Der Stand wird erst freigegeben, wenn alle Schützen entladen und geholstert haben.": "The range is only cleared once every shooter has unloaded and holstered.",
  "Der Stellungswechsel darf ausschließlich mit leerer Waffe erfolgen: Magazin entfernt und Verschluss offen, beziehungsweise Trommel leer und ausgeschwenkt.": "The change of position may only be made with an empty weapon: magazine removed and action open, or cylinder empty and swung out.",
  "Der Veranstalter kann ein Warm-Up von 2:45 Minuten auf 50 m und 1:30 Minuten auf 25 m anbieten; auf Landes- und Deutschen Meisterschaften ist es verpflichtend.": "The organiser may offer a warm-up of 2:45 minutes at 50 m and 1:30 minutes at 25 m; at state and national championships it is mandatory.",
  "Die Begrenzungslinien rechts und links sind zu beachten.": "The boundary lines to the right and left have to be observed.",
  "Die Beobachtung der Wertungsschüsse durch den Schützen ist nicht erlaubt; Fremdbeobachtung und Coaching sind unzulässig.": "The shooter may not spot their own scoring shots; spotting by others and coaching are not allowed.",
  "Die Entfernungen können wahlweise in Metern oder Yards geschossen werden; das ist in der Ausschreibung bekanntzugeben.": "The distances may be shot either in metres or in yards; this has to be stated in the match programme.",
  "Die Geschossenergie muss bei einer E2-Messung mindestens 1200 Joule erreichen.": "The projectile energy has to reach at least 1200 joules in an E2 measurement.",
  "Die Kleinkaliber-Variante DKS 1 – 1020 (C.15A) hat denselben Ablauf; dort wird Match 1 auf 10 m geschossen, die Scheibenentfernungen sind wahlweise 10 m, 15 m oder 25 m. Die Kommandos laufen ebenfalls nach C.8.5.": "The rimfire version DKS 1 – 1020 (C.15A) follows the same course of fire; there match 1 is shot at 10 m and the target distances are 10 m, 15 m or 25 m as chosen. Its commands also follow C.8.5.",
  "Die Mündung zeigt beim Vorzeigen immer in Richtung Geschossfang.": "While showing clear the muzzle always points towards the backstop.",
  "Die Reihenfolge der Matches und Stationen ist einzuhalten.": "The order of the matches and stations has to be kept.",
  "Die Restzeit auf der Auswertekarte des Schützen vermerken.": "Note the remaining time on the shooter's score card.",
  "Die Sammlung führt die Disziplin als „Police Pistol 1 (SM)“; der Ablauf ist der der Super Magnum nach C.6C, nicht der der Police Pistol 1.": "The collection lists this discipline as “Police Pistol 1 (SM)”; its course of fire is the Super Magnum one under C.6C, not that of the Police Pistol 1.",
  "Die Schießhand darf mit der freien Hand unterstützt werden.": "The shooting hand may be supported by the free hand.",
  "Die verbleibende Restzeit wird dem Schützen vor dem Startsignal mitgeteilt (C.17.8).": "The shooter is told the remaining time before the start signal (C.17.8).",
  "Die Waffe wird aus dem Holster genommen, geladen und wieder geholstert. Halbautomatische Pistolen werden grundsätzlich unterladen geholstert und erst zu Beginn der Serie fertiggeladen.": "The weapon is taken from the holster, loaded and holstered again. Semi-automatic pistols are always holstered with an empty chamber and only fully loaded at the start of the string.",
  "Die Waffe wird mit ausgestreckten Armen auf 45 Grad abgesenkt, die Mündung zielt auf den Boden.": "The weapon is lowered to 45 degrees with the arms extended, the muzzle pointing at the ground.",
  "Die Waffe wird mit einer oder beiden Händen gehalten. Unterstützende Hilfsmittel sind untersagt.": "The weapon is held with one or both hands. Supporting aids are not allowed.",
  "Die Waffe wird waagerecht zum Boden gehalten. Die Ellenbogen liegen am Körper an, Ober- und Unterarm bilden einen Winkel von 90 Grad. Die Mündung zielt auf die Scheibe.": "The weapon is held horizontally to the ground. The elbows rest against the body, upper and lower arm forming an angle of 90 degrees. The muzzle points at the target.",
  "Die Zeit stoppt nach dem Holstern der geladenen Waffe.": "Timing stops once the loaded weapon is holstered.",
  "DKS 1 – 1020": "DKS 1 – 1020",
  "DKS 1 – 1020 (Kleinkaliber)": "DKS 1 – 1020 (rimfire)",
  "DKS 2 – 1020": "DKS 2 – 1020",
  "Double Action gilt nicht beim Gebrauch von Selbstladepistolen.": "Double action does not apply when self-loading pistols are used.",
  "Double-Action-Pistole: mit 5 Patronen laden, entspannen, holstern.": "Double-action pistol: load with 5 cartridges, decock, holster.",
  "Ein Verstoß gegen grundlegende Sicherheitsbestimmungen führt zur sofortigen Disqualifikation.": "A breach of the basic safety rules leads to immediate disqualification.",
  "eine oder zwei NPA-Service-Pistol-Scheiben": "one or two NPA Service Pistol targets",
  "Einzige Station, an der der erste Schuss nicht im Double-Action-Modus abgegeben wird (C.17.14).": "The only station where the first round is not fired in double action (C.17.14).",
  "Ersatzweise ein Signal, oder die Scheiben werden weggedreht und nach etwa 5 Sekunden zum Start der Serie wieder hergedreht.": "Alternatively a signal, or the targets are turned away and turned back after about 5 seconds to start the string.",
  "Erst nach Bestätigung durch die Aufsicht wird geholstert.": "Holster only after the range officer has confirmed.",
  "Es dürfen nur sechs Patronen ins Magazin geladen werden.": "Only six cartridges may be loaded into the magazine.",
  "Es gibt keine anerkannten Waffen- oder Munitionsfehler.": "There are no recognised weapon or ammunition malfunctions.",
  "Es gibt keine anerkannten Waffen- und Munitionsfehler; Versager und Fehlfunktionen gehen zu Lasten des Schützen (C.6.8).": "There are no recognised weapon or ammunition malfunctions; misfires and stoppages are at the shooter's expense (C.6.8).",
  "Europäischer Präzisions Parcours (EPP)": "European Precision Course (EPP)",
  "Fertigstellung Station A: Waffe mit ausgestreckten Armen auf 45 Grad abgesenkt. Stationen B und C: Waffe geholstert.": "Ready position on station A: weapon lowered to 45 degrees with the arms extended. Stations B and C: weapon holstered.",
  "Gleiche Distanzen und gleiche Zeiten wie die Kurzwaffenfassung.": "Same distances and same times as the handgun version.",
  "Gleicher Ablauf und gleiche Zeiten wie die Kurzwaffenfassung.": "Same course of fire and same times as the handgun version.",
  "Halbautomatische Pistolen mit offenem Verschluss und dem zuletzt benutzten Magazin vorzeigen.": "Show semi-automatic pistols with the action open and the magazine last used.",
  "Halbautomatische Pistolen werden mit offenem Verschluss vorgezeigt, dazu das zuletzt benutzte Magazin.": "Semi-automatic pistols are shown with the action open, together with the magazine last used.",
  "Hilfsmittel zum Training, keine Wettkampfdisziplin: eine reine Uhr über 90 und 165 Sekunden. Deshalb ohne Kommandofolge und ohne Ansage.": "A training aid, not a competition discipline: a plain clock over 90 and 165 seconds. That is why it carries no command sequence and no announcement.",
  "höchstens sechs Patronen in Waffe, Speedloader oder Magazin": "at most six cartridges in weapon, speedloader or magazine",
  "Ist ein Stand für 7 m nicht zugelassen, darf stattdessen auf 10 m geschossen werden.": "If a range is not approved for 7 m, 10 m may be shot instead.",
  "Ist jemand nicht fertig? - ACHTUNG!": "Is anyone not ready? - STAND BY!",
  "Kann durch ein anderes Signal ersetzt werden, etwa das Wegdrehen der Scheiben. Die Serie beginnt mit dem Herdrehen oder einem anderen Startsignal.": "May be replaced by another signal, for instance turning the targets away. The string begins when they turn back or with another start signal.",
  "Keine Kommandofolge": "No command sequence",
  "Kleinkaliber .22 lr": "Rimfire .22 lr",
  "Kleinkaliber-Fassung der 1020, durchgeführt in Anlehnung an die Regeln der NASRPC Ireland.": "Rimfire version of the 1020, run along the lines of the NASRPC Ireland rules.",
  "Kleinkaliber-Kurzwaffe": "Rimfire handgun",
  "Kleinkaliber-Langwaffe": "Rimfire long gun",
  "kniend": "kneeling",
  "Kniend auf einem Knie, das andere der Scheibe zugewandt. Die Gesäßbacken können auf den Absätzen oder seitlich auf dem Fuß aufliegen, dürfen den Boden aber nicht berühren. Der Arm darf durch das zur Scheibe zeigende Knie stabilisiert werden, die Waffe selbst nicht. Alternativ kniend auf beiden Knien, dann deutlich vom Boden entfernt und ohne weitere Unterstützung.": "Kneeling on one knee, the other facing the target. The buttocks may rest on the heels or sideways on the foot, but must not touch the ground. The arm may be steadied on the knee facing the target, the weapon itself may not. Alternatively kneeling on both knees, then clearly clear of the ground and without any further support.",
  "Kniend frei": "Kneeling unsupported",
  "Kniend mit Pfosten": "Kneeling at the barricade",
  "Kurzwaffe": "Handgun",
  "Laden, fertigmachen und holstern!": "Load, make ready and holster!",
  "Langwaffe": "Long gun",
  "Langwaffenfassung mit Sports Carbine. Weicht von der Kurzwaffen-PP1 auf 15 m und 10 m ab: 3 statt 2 Sekunden je Intervall. Deshalb ein eigener Satz.": "Long gun version with the sports carbine. Differs from the handgun PP1 at 15 m and 10 m: 3 instead of 2 seconds per interval. That is why it has a set of its own.",
  "Langwaffenfassung mit Unterhebelrepetierer. Weicht von der Kurzwaffen-PP1 auf 10 m ab: 3 statt 2 Sekunden je Intervall. Deshalb ein eigener Satz.": "Long gun version with the lever action rifle. Differs from the handgun PP1 at 10 m: 3 instead of 2 seconds per interval. That is why it has a set of its own.",
  "Leere Waffe und gegebenenfalls Magazin der Aufsicht zur Sicherheitsüberprüfung vorzeigen, danach holstern.": "Show the empty weapon, and the magazine where applicable, to the range officer for the safety check, then holster.",
  "liegend": "prone",
  "Liegend": "Prone",
  "Match 1 — 10 m": "Match 1 — 10 m",
  "Match 1 — 15 m": "Match 1 — 15 m",
  "Match 1: 10 m — 20 Sekunden — nur double action — 2 × 6 Schüsse stehend frei. Danach 15 m, 20 Sekunden, 2 × 6 Schüsse stehend frei.": "Match 1: 10 m — 20 seconds — double action only — 2 × 6 rounds standing unsupported. Then 15 m, 20 seconds, 2 × 6 rounds standing unsupported.",
  "Match 1: 15 Meter/Yards - 20 Sekunden - nur double action": "Match 1: 15 metres/yards - 20 seconds - double action only",
  "Match 1: 7 m — 20 Sekunden — nur double action — 12 Schüsse stehend frei. Danach 15 m, 20 Sekunden, 12 Schüsse stehend frei.": "Match 1: 7 m — 20 seconds — double action only — 12 rounds standing unsupported. Then 15 m, 20 seconds, 12 rounds standing unsupported.",
  "Match 1: 7 m — 20 Sekunden — nur double action — 2 × 6 Schüsse stehend frei. Danach 15 m, 20 Sekunden, 2 × 6 Schüsse stehend frei.": "Match 1: 7 m — 20 seconds — double action only — 2 × 6 rounds standing unsupported. Then 15 m, 20 seconds, 2 × 6 rounds standing unsupported.",
  "Match 1: 7 Meter/Yards - 20 Sekunden - nur double action": "Match 1: 7 metres/yards - 20 seconds - double action only",
  "Match 1: Wir gehen auf 15 Meter": "Match 1: We move to 15 metres",
  "Match 1: Wir gehen auf 7 Meter": "Match 1: We move to 7 metres",
  "Match 2 — 25 m": "Match 2 — 25 m",
  "Match 2: 25 m — 90 Sekunden — nur double action — 6 kniend frei, 6 stehend linke Hand Pfosten links, 6 stehend rechte Hand Pfosten rechts.": "Match 2: 25 m — 90 seconds — double action only — 6 kneeling unsupported, 6 standing left hand left barricade, 6 standing right hand right barricade.",
  "Match 2: 25 Meter/Yards - 90 Sekunden - nur double action": "Match 2: 25 metres/yards - 90 seconds - double action only",
  "Match 2: Wir gehen auf 25 Meter": "Match 2: We move to 25 metres",
  "Match 3 — 25 m, 1. Durchgang": "Match 3 — 25 m, 1st run",
  "Match 3 — 25 m, 2. Durchgang": "Match 3 — 25 m, 2nd run",
  "Match 3:": "Match 3:",
  "Match 3: 25 m — 35 Sekunden — nur double action — 2 × 6 Schüsse stehend frei, danach Wiederholung.": "Match 3: 25 m — 35 seconds — double action only — 2 × 6 rounds standing unsupported, then a repeat.",
  "Match 3: 50 m — 165 Sekunden — auch single action — 6 sitzend, 6 liegend, 6 stehend linke Hand Pfosten links, 6 stehend rechte Hand Pfosten rechts.": "Match 3: 50 m — 165 seconds — single action also permitted — 6 seated, 6 prone, 6 standing left hand left barricade, 6 standing right hand right barricade.",
  "Match 3: 50 Meter/Yards - 165 Sekunden - auch single action erlaubt": "Match 3: 50 metres/yards - 165 seconds - single action also permitted",
  "Match 3: Wir bleiben auf 25 Meter": "Match 3: We stay at 25 metres",
  "Match 4 — 25 m": "Match 4 — 25 m",
  "Match 4: 25 m — 165 Sekunden — nur double action — 6 sitzend, 6 kniend frei, 6 stehend linke Hand Pfosten links, 6 stehend rechte Hand Pfosten rechts.": "Match 4: 25 m — 165 seconds — double action only — 6 seated, 6 kneeling unsupported, 6 standing left hand left barricade, 6 standing right hand right barricade.",
  "Match 4: 25 m — 35 Sekunden — nur double action — 12 Schüsse stehend frei, danach Wiederholung.": "Match 4: 25 m — 35 seconds — double action only — 12 rounds standing unsupported, then a repeat.",
  "Match 4: 25 Meter/Yards - 35 Sekunden - nur double action": "Match 4: 25 metres/yards - 35 seconds - double action only",
  "Match 4: Wir bleiben auf 25 Meter": "Match 4: We stay at 25 metres",
  "Match 5 - Station 1:": "Match 5 - Station 1:",
  "Match 5 - Station 2:": "Match 5 - Station 2:",
  "Match 5 - Station 3:": "Match 5 - Station 3:",
  "Match 5 - Station 4:": "Match 5 - Station 4:",
  "Match 5 — 25 m, 1. Durchgang": "Match 5 — 25 m, 1st run",
  "Match 5 — 25 m, 2. Durchgang": "Match 5 — 25 m, 2nd run",
  "Match 5, 60 Schuss: Station 1 bei 7 m in 20 s, Station 2 bei 25 m in 90 s, Station 3 bei 50 m in 165 s, Station 4 bei 25 m in 12 s mit 6 Schüssen stehend frei.": "Match 5, 60 rounds: station 1 at 7 m in 20 s, station 2 at 25 m in 90 s, station 3 at 50 m in 165 s, station 4 at 25 m in 12 s with 6 rounds standing unsupported.",
  "Match 5:": "Match 5:",
  "Match 5: 25 m — 12 Sekunden — nur double action — 6 Schüsse stehend frei, danach ein zweiter Durchgang mit 6 Schüssen stehend frei.": "Match 5: 25 m — 12 seconds — double action only — 6 rounds standing unsupported, then a second run with 6 rounds standing unsupported.",
  "Match 5: Wir bleiben auf 25 Meter": "Match 5: We stay at 25 metres",
  "mindestens eine BDMP-1500-Scheibe je Schütze und Match": "at least one BDMP 1500 target per shooter and match",
  "Nach dem fünften Schuss erneut laden, spannen und beidhändig auf die obere linke Ringscheibe schießen.": "After the fifth round, load again, cock and fire two-handed at the upper left scoring target.",
  "Nach dem fünften Schuss selbstständig laden und entspannen, dann mit der linken Hand links am Pfosten vorbei.": "After the fifth round, load and decock without prompting, then shoot with the left hand past the left-hand side of the barricade.",
  "Nach dem letzten Schuss aufstehen, dann laden, entspannen und holstern.": "After the last round stand up, then load, decock and holster.",
  "Nach dem letzten Schuss laden, entspannen und holstern.": "After the last round load, decock and holster.",
  "Nach dem letzten Schuss nach vorn aufstehen, dann selbstständig laden, entspannen und holstern.": "After the last round stand up forwards, then load, decock and holster without prompting.",
  "Nach dem letzten Schuss wird die Gesamtzeit gestoppt.": "After the last round the overall time is stopped.",
  "Nach der Auswertung die Einschusslöcher mit 10 weißen Schusslochpflastern abkleben.": "After scoring, cover the bullet holes with 10 white patches.",

  // ── Disziplinnamen, Stationen, Restliches ───────────────────────────────
  "Nach der Meldung „Sicherheit“ auf die 1-m-Linie zur Trefferaufnahme vorgehen.": "After the call “the line is clear”, move forward to the 1 m line for scoring.",
  "Nach Name erkennen": "Detect from the name",
  "nach Wettkampfart": "according to the type of competition",
  "Nachgeladen wird erst nach dem Wechsel der Schießstellung.": "Reloading only takes place after the change of position.",
  "Nachladen aus einer Shooter’s Box am Boden ist während der Serie nicht erlaubt.": "Reloading from a shooter’s box on the ground is not allowed during the string.",
  "NPA Service Pistol (30M1)": "NPA Service Pistol (30M1)",
  "NPA Service Pistol (LAR)": "NPA Service Pistol (LAR)",
  "NPA Service Pistol (SpCb)": "NPA Service Pistol (SpCb)",
  "NPA Service Pistole (A-B-OS)": "NPA Service Pistol (A-B-OS)",
  "Nur für die 40- und 48-Schuss-Matches. Der Pfosten ist zu benutzen, die Waffe darf ihn nicht berühren. Der Schütze kniet links hinter dem Pfosten, wenn er rechts schießt, und umgekehrt.": "Only for the 40- and 48-round matches. The barricade has to be used, the weapon must not touch it. The shooter kneels to the left behind the barricade when shooting on the right, and the other way round.",
  "Nur serienmäßige, unveränderte Waffen. Mündungsbremsen sind ausdrücklich verboten.": "Standard, unmodified weapons only. Muzzle brakes are expressly forbidden.",
  "Pistole: nach dem fünften Schuss selbstständig Magazinwechsel. Revolver: nach dem vierten Schuss 6 Patronen nachladen.": "Pistol: change the magazine after the fifth round without prompting. Revolver: reload 6 cartridges after the fourth round.",
  "Police Pistol / NPA / SM (C.6.10)": "Police Pistol / NPA / SM (C.6.10)",
  "Police Pistol 1": "Police Pistol 1",
  "Police Pistol 1 (30M1 - SpCb)": "Police Pistol 1 (30M1 - SpCb)",
  "Police Pistol 1 (A-B-OS)": "Police Pistol 1 (A-B-OS)",
  "Police Pistol 1 (LAR)": "Police Pistol 1 (LAR)",
  "Police Pistol 1 (SM)": "Police Pistol 1 (SM)",
  "Police Pistol 1 (Sports Carbine)": "Police Pistol 1 (Sports Carbine)",
  "Police Pistol 2": "Police Pistol 2",
  "Police Pistol 2 (PP2)": "Police Pistol 2 (PP2)",
  "Police Pistol 3 (Carry Gun)": "Police Pistol 3 (Carry Gun)",
  "Police Pistol 4 (Pocket Gun)": "Police Pistol 4 (Pocket Gun)",
  "Police Pistol, NPA Service Pistol, Super Magnum": "Police Pistol, NPA Service Pistol, Super Magnum",
  "PP-1-Scheibe": "PP-1 target",
  "PP-1-Scheibe; auf 10 m und 25 m auf 50 % verkleinert": "PP-1 target; reduced to 50 % at 10 m and 25 m",
  "Probeschüsse liegen im Ermessen des Veranstalters.": "Sighting shots are at the organiser's discretion.",
  "Probeschüsse nur auf Station B: 6 Schüsse in 2 Minuten.": "Sighting shots on station B only: 6 rounds in 2 minutes.",
  "Probeschüsse sind nicht erlaubt (C.6.6).": "Sighting shots are not allowed (C.6.6).",
  "Revolver mit ausgeklappter Trommel und den zuletzt enthaltenen Hülsen vorzeigen.": "Show revolvers with the cylinder swung out and the cases last in it.",
  "Revolver werden mit ausgeklappter Trommel vorgezeigt, dazu die zuletzt in der Trommel befindlichen Hülsen.": "Revolvers are shown with the cylinder swung out, together with the cases last held in it.",
  "Revolver: mit 4 Patronen laden.": "Revolver: load with 4 cartridges.",
  "Scheibe: mindestens eine BDMP 1500 reduziert je Schütze und Match.": "Target: at least one reduced BDMP 1500 per shooter and match.",
  "Scheibenentfernung wahlweise 10 m, 15 m oder 25 m mit den Toleranzen nach C.15A.5.": "Target distance 10 m, 15 m or 25 m as chosen, within the tolerances of C.15A.5.",
  "Scheibenentfernungen wahlweise 7 m, 15 m oder 25 m mit den Toleranzen nach C.21.": "Target distances 7 m, 15 m or 25 m as chosen, within the tolerances of C.21.",
  "Sicherheitskontrolle durch den RO, danach holstern.": "Safety check by the range officer, then holster.",
  "Single-Action-Pistole und Pistolen ohne Entspannhebel: nur das gefüllte Magazin einsetzen, dann holstern.": "Single-action pistols and pistols without a decocker: insert the filled magazine only, then holster.",
  "sitzend": "seated",
  "Sitzend": "Seated",
  "Sports Carbine PP2": "Sports Carbine PP2",
  "Sports Carbine PP2 (Langwaffe)": "Sports Carbine PP2 (long gun)",
  "Stage 1 - 25 Meter": "Stage 1 - 25 metres",
  "Stage 1: 15m": "Stage 1: 15m",
  "Stage 1: 20m": "Stage 1: 20m",
  "Stage 1: 25m": "Stage 1: 25m",
  "Stage 2 - 20 Meter": "Stage 2 - 20 metres",
  "Stage 2: 10m": "Stage 2: 10m",
  "Stage 2: 15m": "Stage 2: 15m",
  "Stage 2: 15m (1. Durchgang)": "Stage 2: 15m (1st run)",
  "Stage 2: 15m (2. Durchgang)": "Stage 2: 15m (2nd run)",
  "Stage 2: 20m": "Stage 2: 20m",
  "Stage 3 - 15 Meter": "Stage 3 - 15 metres",
  "Stage 3: 10m": "Stage 3: 10m",
  "Stage 3: 15m": "Stage 3: 15m",
  "Stage 3: 7m": "Stage 3: 7m",
  "Stage 4 - 10 Meter": "Stage 4 - 10 metres",
  "Stage 4: 10m": "Stage 4: 10m",
  "Station 1": "Station 1",
  "Station 2": "Station 2",
  "Station 3": "Station 3",
  "Station 4": "Station 4",
  "Station 5a": "Station 5a",
  "Station 5b": "Station 5b",
  "Station 6": "Station 6",
  "Station A — 10 m, 1. Durchgang": "Station A — 10 m, 1st run",
  "Station A — 10 m, 2. Durchgang": "Station A — 10 m, 2nd run",
  "Station A, 10 m: zweimal 6 Schuss stehend freihändig in je 7 Sekunden.": "Station A, 10 m: twice 6 rounds standing unsupported, 7 seconds each.",
  "Station A, 10 m: zweimal 6 Schüsse in 5 Sekunden, stehend frei, ein- oder beidhändig.": "Station A, 10 m: twice 6 rounds in 5 seconds, standing unsupported, one- or two-handed.",
  "Station A: 10m": "Station A: 10m",
  "Station A: Die Waffe wird mit ausgestreckten Armen auf 45 Grad abgesenkt, die Mündung zielt auf den Boden. Stationen B und C: Die Waffe ist geholstert, halbautomatische Pistolen unterladen.": "Station A: the weapon is lowered to 45 degrees with the arms extended, the muzzle pointing at the ground. Stations B and C: the weapon is holstered, semi-automatic pistols with an empty chamber.",
  "Station B — 50 m": "Station B — 50 m",
  "Station B, 50 m: 140 Sekunden, auch single action — 6 liegend, 6 kniend, 6 stehend linke Hand Pfosten links, 6 stehend rechte Hand Pfosten rechts.": "Station B, 50 m: 140 seconds, single action also permitted — 6 prone, 6 kneeling, 6 standing left hand left barricade, 6 standing right hand right barricade.",
  "Station B, 50 m: 6 Schüsse liegend, 6 kniend oder sitzend, 6 stehend linke Hand am Pfosten links, 6 stehend rechte Hand am Pfosten rechts. Gesamtzeit 3 Minuten.": "Station B, 50 m: 6 rounds prone, 6 kneeling or seated, 6 standing left hand at the left barricade, 6 standing right hand at the right barricade. Overall time 3 minutes.",
  "Station B: 50m": "Station B: 50m",
  "Station C — 25 m": "Station C — 25 m",
  "Station C, 25 m: 6 Schüsse stehend frei, 6 kniend oder sitzend, 6 stehend rechte Hand am Pfosten rechts, 6 stehend linke Hand am Pfosten links. Gesamtzeit 2 Minuten.": "Station C, 25 m: 6 rounds standing unsupported, 6 kneeling or seated, 6 standing right hand at the right barricade, 6 standing left hand at the left barricade. Overall time 2 minutes.",
  "Station C, 25 m: 90 Sekunden, auch single action — 6 stehend frei, 6 kniend, 6 stehend rechte Hand Pfosten rechts, 6 stehend linke Hand Pfosten links.": "Station C, 25 m: 90 seconds, single action also permitted — 6 standing unsupported, 6 kneeling, 6 standing right hand right barricade, 6 standing left hand left barricade.",
  "Station C: 25m": "Station C: 25m",
  "stehend": "standing",
  "stehend am Pfosten": "standing at the barricade",
  "Stehend am Pfosten": "Standing at the barricade",
  "Stehend frei": "Standing unsupported",
  "Stellung stehend frei, beidhändiges Halten ist erlaubt (C.6.5).": "Position standing unsupported, holding with both hands is permitted (C.6.5).",
  "Stellungen und Fertigstellung nach C.8.4 beziehungsweise C.8.7.": "Positions and ready position according to C.8.4 and C.8.7 respectively.",
  "Super Magnum": "Super Magnum",
  "Verbleibende Restzeit ansagen!": "Announce the remaining time!",
  "Waffen laden und fertig machen.": "Load and make ready.",
  "Weicht von der Kurzwaffen-PP2 ab: Station A 7 statt 5 Sekunden, Station B 140 statt 180 Sekunden, Station C 90 statt 120 Sekunden. Deshalb ein eigener Satz.": "Differs from the handgun PP2: station A 7 instead of 5 seconds, station B 140 instead of 180 seconds, station C 90 instead of 120 seconds. That is why it has a set of its own.",
  "Weicht von der Kurzwaffenfassung nach C.7 nur auf Station 4 ab: 8 statt 6 Sekunden.": "Differs from the handgun version under C.7 on station 4 only: 8 instead of 6 seconds.",
  "Wer nicht fertig ist, meldet das klar und deutlich. Dann lautet das Kommando „Nicht fertig!“ („Not ready!“).": "Anyone who is not ready says so clearly and audibly. The command is then “Nicht fertig!” (“Not ready!”).",
  "Wer nicht fertig ist, zeigt das klar und deutlich an. Dann lautet das Kommando „Nicht fertig!“ („The line is not ready“).": "Anyone who is not ready indicates it clearly and audibly. The command is then “Nicht fertig!” (“The line is not ready”).",
  "Wiederholung": "Repeat",
  "Zeitkontrolle Schütze": "Shooter's time check",
  "Zu keinem Zeitpunkt dürfen Waffe, Speedloader oder Magazin mit mehr als sechs Patronen geladen sein.": "At no point may the weapon, a speedloader or a magazine hold more than six cartridges.",
  "zwei NPA-Service-Pistol-Scheiben": "two NPA Service Pistol targets",
  "Zweites Magazin mit 5 Patronen bzw. Speedloader mit 6 Patronen bereithalten.": "Have a second magazine with 5 cartridges, or a speedloader with 6, ready.",
  "Zweites Signal nach 13 Sekunden, Dauer 2 Sekunden. Jeder Schuss nach Ende des Signals wird nicht gewertet.": "Second signal after 13 seconds, lasting 2 seconds. Any round fired after the signal ends does not count.",
  "Zweites Signal nach 8 Sekunden, Dauer 2 Sekunden. Jeder Schuss nach Ende des Signals wird nicht gewertet.": "Second signal after 8 seconds, lasting 2 seconds. Any round fired after the signal ends does not count.",

  // ── EPP: Varianten und allgemeine Hinweise ──────────────────────────────
  "EPP Kurzwaffe": "EPP handgun",
  "EPP Rifle .223 / EPP Carbine": "EPP Rifle .223 / EPP Carbine",
  "Gleiche Stationen und gleiche Zeiten wie die Kurzwaffenfassung.": "Same stations and same times as the handgun version.",
  "Kommando an Station 1: „Teilladen und fertigmachen“. Die Waffe wird mit dem ersten Magazin teilgeladen und die Sicherheitsfahne entfernt; das zweite Magazin mit 5 Patronen wird bereitgehalten.": "Command on station 1: “Partially load and make ready”. The weapon is partially loaded with the first magazine and the safety flag is removed; the second magazine with 5 cartridges is held ready.",
  "Auf das Startsignal geht der Schütze in Anschlag, lädt fertig und schießt. Nach dem fünften Schuss wird selbstständig das Magazin gewechselt.": "On the start signal the shooter takes up the position, finishes loading and fires. After the fifth round the magazine is changed without prompting.",
  "Nach dem letzten Schuss wird die Sicherheitsfahne ins Patronenlager eingeführt, das Magazin entnommen und zum Vorzeigen in der Hand gehalten. Der Lauf zeigt 45 Grad nach unten in Richtung Geschossfang.": "After the last round the safety flag is inserted into the chamber, the magazine is removed and held in the hand to be shown. The barrel points 45 degrees down towards the backstop.",
  "An Station 6 wird nicht zwischen ein- und beidhändig unterschieden, sondern zwischen rechter und linker Hand am Abzug.": "On station 6 the distinction is not between one- and two-handed, but between the right and the left hand on the trigger.",
  "Vor dem Startsignal steht der Schütze aufrecht in Richtung Scheibe, die Arme hängen zwanglos herab.": "Before the start signal the shooter stands upright facing the target, arms hanging down loosely.",
  "Die Hände berühren weder Waffe noch Holster, bis das Startsignal gegeben wird.": "The hands touch neither weapon nor holster until the start signal is given.",
  "Laden, Entspannen und Holstern erfolgen ohne Ausnahme im Stehen.": "Loading, decocking and holstering are done standing, without exception.",
  "Das Laden der Waffe erfolgt ausschließlich im nichtgeholsterten Zustand.": "The weapon is only ever loaded out of the holster.",
  "Bei einer Störung hebt der Schütze die freie Hand und meldet deutlich „Störung“. Die Zeit wird gestoppt.": "In case of a stoppage the shooter raises the free hand and calls out “Störung” clearly. The time is stopped.",
}

/**
 * Übersetzt einen Text zeilenweise. Ohne Eintrag bleibt die Zeile stehen —
 * lieber der deutsche Originalsatz als eine Lücke im Ablauf.
 */
export function uebersetze(text, locale = 'de') {
  if (locale === 'de' || text == null) return text
  return String(text)
    .split('\n')
    .map(zeile => {
      const roh = zeile.trim()
      if (!roh) return zeile
      return TEXTE_EN[roh] ?? zeile
    })
    .join('\n')
}

/** Dieselbe Übersetzung für eine Liste von Texten. */
export function uebersetzeListe(liste, locale = 'de') {
  if (locale === 'de' || !Array.isArray(liste)) return liste
  return liste.map(t => uebersetze(t, locale))
}

/** Für den Test: Texte ohne englische Fassung. */
export function fehlendeTexte(texte) {
  return [...new Set(texte)]
    .map(t => String(t ?? '').trim())
    .filter(Boolean)
    .filter(t => !(t in TEXTE_EN))
}
